/**
 * TOML import and export for `starship.toml`.
 *
 * Two properties matter more than pretty output:
 *
 *  - **Nothing is dropped.** Options, modules and root keys the builder does
 *    not understand survive an import → export round trip untouched. A user
 *    pasting a config full of options this app has never heard of must get it
 *    back intact.
 *  - **Exports are minimal by default.** Only values that differ from
 *    starship's defaults are written, which is what people keep in a dotfiles
 *    repo. `full: true` writes the fully resolved config instead.
 *
 * Output is deterministic: no timestamp in the header, and a fixed key order,
 * so re-exporting an unchanged config produces an identical file.
 */

import { TomlError, parse, stringify } from "smol-toml";
import { DEFAULT_CONFIG } from "./defaults";
import { ROOT_OPTIONS, getModuleSchemas } from "./schema";
import type { StarshipConfig } from "@/lib/engine/prompt";

export type ParseResult =
  | { ok: true; config: StarshipConfig }
  | { ok: false; error: string; line?: number };

export interface SerialiseOptions {
  /** Emit every resolved value, not just the ones that differ from defaults. */
  full?: boolean;
  /**
   * Defaults to diff against. Defaults to the schema-derived config; pass
   * `resolveDefaults(modules)` to diff against the engine registry instead.
   */
  defaults?: StarshipConfig;
  /** Set false to omit the leading comment block. */
  header?: boolean;
}

const HEADER = [
  "# starship.toml — generated by Starship Prompt Builder",
  "# Save to ~/.config/starship.toml (or $STARSHIP_CONFIG).",
  "# Reference: https://starship.rs/config/",
];

const ROOT_KEYS = ROOT_OPTIONS.map((option) => option.key);
const ROOT_KEY_SET = new Set<string>(ROOT_KEYS);
const MODULE_ORDER = getModuleSchemas().map((module) => module.name);

function isTable(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Structural equality, enough for the JSON-shaped values TOML produces. */
function deepEqual(a: unknown, b: unknown): boolean {
  if (a === b) return true;
  if (a instanceof Date && b instanceof Date) return a.getTime() === b.getTime();
  if (Array.isArray(a) && Array.isArray(b)) {
    return a.length === b.length && a.every((item, i) => deepEqual(item, b[i]));
  }
  if (isTable(a) && isTable(b)) {
    const keys = Object.keys(a);
    return (
      keys.length === Object.keys(b).length &&
      keys.every((key) => Object.hasOwn(b, key) && deepEqual(a[key], b[key]))
    );
  }
  return false;
}

export function parseConfig(text: string): ParseResult {
  let parsed: unknown;
  try {
    parsed = parse(text);
  } catch (err) {
    if (err instanceof TomlError) {
      return { ok: false, error: err.message, line: err.line };
    }
    return { ok: false, error: (err as Error).message };
  }

  if (!isTable(parsed)) {
    return { ok: false, error: "A starship config must be a table of options." };
  }

  return { ok: true, config: parsed as StarshipConfig };
}

/**
 * Root keys in a stable order: `$schema` (starship's own convention), then the
 * documented prompt-wide options, then anything else the user had.
 */
function orderedRootKeys(config: StarshipConfig): string[] {
  const present = new Set(Object.keys(config));
  const ordered: string[] = [];

  if (present.has("$schema")) ordered.push("$schema");
  for (const key of ROOT_KEYS) if (present.has(key)) ordered.push(key);

  const seen = new Set(ordered);
  const rest = [...present].filter(
    (key) => !seen.has(key) && !isTable(config[key]) && key !== "$schema",
  );
  return [...ordered, ...rest.sort()];
}

/** Module tables in schema order, with unrecognised tables appended. */
function orderedTableKeys(config: StarshipConfig): string[] {
  const present = new Set(
    Object.keys(config).filter(
      (key) => isTable(config[key]) && !ROOT_KEY_SET.has(key) && key !== "$schema",
    ),
  );

  const known = MODULE_ORDER.filter((name) => present.has(name));
  const unknown = [...present].filter((key) => !MODULE_ORDER.includes(key)).sort();
  return [...known, ...unknown];
}

/**
 * Keeps the options of one module table that differ from its defaults.
 *
 * Options with no default — because the option, or the whole module, is
 * unknown to the schema — always differ, which is what preserves them.
 */
function minimalTable(
  table: Record<string, unknown>,
  defaults: unknown,
): Record<string, unknown> {
  const defaultTable = isTable(defaults) ? defaults : {};
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(table)) {
    if (value === undefined) continue;
    if (!deepEqual(value, defaultTable[key])) out[key] = value;
  }
  return out;
}

function buildMinimal(config: StarshipConfig, defaults: StarshipConfig): StarshipConfig {
  const out: StarshipConfig = {};

  for (const key of orderedRootKeys(config)) {
    const value = config[key];
    if (value === undefined) continue;
    if (!deepEqual(value, defaults[key])) out[key] = value;
  }

  for (const key of orderedTableKeys(config)) {
    const table = minimalTable(config[key] as Record<string, unknown>, defaults[key]);
    // A table that reduces to nothing says nothing; drop the header too.
    if (Object.keys(table).length > 0) out[key] = table;
  }

  return out;
}

function buildFull(config: StarshipConfig, defaults: StarshipConfig): StarshipConfig {
  const merged: StarshipConfig = { ...defaults };
  for (const [key, value] of Object.entries(config)) {
    if (value === undefined) continue;
    const base = merged[key];
    merged[key] =
      isTable(value) && isTable(base) ? { ...base, ...value } : value;
  }

  const out: StarshipConfig = {};
  for (const key of orderedRootKeys(merged)) {
    if (merged[key] !== undefined) out[key] = merged[key];
  }
  for (const key of orderedTableKeys(merged)) {
    const table = merged[key] as Record<string, unknown>;
    // `env_var` and `custom` default to an empty map of instances; a bare
    // `[env_var]` header would be noise.
    if (Object.keys(table).length > 0) out[key] = table;
  }
  return out;
}

export function serialiseConfig(
  config: StarshipConfig,
  opts: SerialiseOptions = {},
): string {
  const { full = false, defaults = DEFAULT_CONFIG, header = true } = opts;
  const shaped = full ? buildFull(config, defaults) : buildMinimal(config, defaults);

  const body = stringify(shaped).trimEnd();
  if (!header) return body.length > 0 ? `${body}\n` : "";
  const lines = body.length > 0 ? [...HEADER, "", body] : HEADER;
  return `${lines.join("\n")}\n`;
}
